que. TOP 3 STORES IN EACH STATE

code:

SELECT state, location_name, SUM(TOTAL_SELLING_PRICE_WITHOUT_GST) AS total_sales 
FROM KSF_SOPHIA_DATA_INTELLIGENCE_HUB_PROD.COMMON_DIMENSIONS.DIM_LOCATION DL
INNER JOIN KSF_SOPHIA_DATA_INTELLIGENCE_HUB_PROD.SALES.FACT_SALES_DETAIL FSD 
ON DL.SK_LOCATION_ID = FSD.FK_LOCATION_ID 
WHERE EXTRACT(MONTH FROM FSD.TRANSACTION_TIMESTAMP) = 3 AND EXTRACT(YEAR FROM FSD.TRANSACTION_TIMESTAMP) = 2023 
GROUP BY state, location_name 
QUALIFY ROW_NUMBER() OVER ( PARTITION BY state 
ORDER BY SUM(TOTAL_SELLING_PRICE_WITHOUT_GST) DESC ) <= 3 
ORDER BY state, total_sales DESC, location_name;


que 2) At what day of the week/ hour of the day maximum instore transactions happen in top 1 store in each state

code:

SELECT state, location_name, location_code, day_of_week, hour_of_day, total_transactions
FROM (
SELECT COUNT(CONCAT(FSD.DD_TRANSACTION_ID, '_', FSD.DD_TRANSACTION_NUMBER)) AS total_transactions, DL.STATE, DL.LOCATION_NAME, DL.LOCATION_CODE, DAYOFWEEK(FSD.TRANSACTION_TIMESTAMP) AS day_of_week, HOUR(FSD.TRANSACTION_TIMESTAMP) AS hour_of_day,
ROW_NUMBER() OVER (PARTITION BY DL.STATE 
ORDER BY SUM(TOTAL_SELLING_PRICE_WITHOUT_GST) DESC) AS rn
FROM KSF_SOPHIA_DATA_INTELLIGENCE_HUB_PROD.COMMON_DIMENSIONS.DIM_LOCATION DL
INNER JOIN KSF_SOPHIA_DATA_INTELLIGENCE_HUB_PROD.SALES.FACT_SALES_DETAIL FSD
ON DL.SK_LOCATION_ID = FSD.FK_LOCATION_ID
WHERE FSD.FK_SOURCE_SYSTEM_ID = '15' AND YEAR(FSD.TRANSACTION_TIMESTAMP) = '2023' AND MONTH(FSD.TRANSACTION_TIMESTAMP) = '03' AND DAY(FSD.TRANSACTION_TIMESTAMP) = '02'
GROUP BY DL.STATE, DL.LOCATION_NAME, DL.LOCATION_CODE, day_of_week, hour_of_day
) AS s
WHERE rn = 1
ORDER BY state;


que 3) top selling product in each top store

code:

SELECT FSD.FK_PRODUCT_ID, DL.state, DL.location_name, SUM(FSD.TOTAL_SELLING_PRICE_WITHOUT_GST) AS total_sales
FROM KSF_SOPHIA_DATA_INTELLIGENCE_HUB_PROD.COMMON_DIMENSIONS.DIM_LOCATION DL
INNER JOIN KSF_SOPHIA_DATA_INTELLIGENCE_HUB_PROD.SALES.FACT_SALES_DETAIL FSD 
ON DL.SK_LOCATION_ID = FSD.FK_LOCATION_ID
WHERE EXTRACT(MONTH FROM FSD.TRANSACTION_TIMESTAMP) = 3 AND EXTRACT(YEAR FROM FSD.TRANSACTION_TIMESTAMP) = 2023
AND DL.location_name IN (
SELECT location_name 
FROM (
SELECT state, location_name, SUM(FSD.TOTAL_SELLING_PRICE_WITHOUT_GST) AS total_sales
FROM KSF_SOPHIA_DATA_INTELLIGENCE_HUB_PROD.COMMON_DIMENSIONS.DIM_LOCATION DL
INNER JOIN KSF_SOPHIA_DATA_INTELLIGENCE_HUB_PROD.SALES.FACT_SALES_DETAIL FSD ON DL.SK_LOCATION_ID = FSD.FK_LOCATION_ID
WHERE EXTRACT(MONTH FROM FSD.TRANSACTION_TIMESTAMP) = 3 AND EXTRACT(YEAR FROM FSD.TRANSACTION_TIMESTAMP) = 2023
GROUP BY state, location_name
QUALIFY ROW_NUMBER() OVER (PARTITION BY state 
ORDER BY SUM(FSD.TOTAL_SELLING_PRICE_WITHOUT_GST) DESC) <= 1
    ) top_1_locations
)
GROUP BY FSD.FK_PRODUCT_ID, DL.state, DL.location_name
QUALIFY ROW_NUMBER() OVER (PARTITION BY DL.state, DL.location_name 
ORDER BY SUM(FSD.TOTAL_SELLING_PRICE_WITHOUT_GST) DESC) <= 1
ORDER BY DL.state, DL.location_name, total_sales DESC, FSD.FK_PRODUCT_ID;


que) customer frequency online and offline

code:


--OFFLINE
SELECT s.fk_kmart_customer_id,  s.average_basket_size, s.frequency, s.high_spent_category, s.state
FROM (
SELECT AG.fk_kmart_customer_id,  AG.average_basket_size, AG.frequency,  AG.high_spent_category, AG.state,
ROW_NUMBER() OVER (PARTITION BY AG.state 
ORDER BY AG.frequency DESC) AS rn
FROM KSF_SOPHIA_DATA_INTELLIGENCE_HUB_PROD.SALES.AGG_CUSTOMER_INSIGHTS AG
INNER JOIN KSF_SOPHIA_DATA_INTELLIGENCE_HUB_PROD.SALES.FACT_SALES_DETAIL FSD 
ON AG.SK_AGG_CUSTOMER_INSIGHTS = FSD.FK_CUSTOMER_ID
WHERE FSD.FK_SOURCE_SYSTEM_ID = 15
) AS s
WHERE s.rn <= 1
ORDER BY s.state, s.frequency DESC
 


--  ONLINE
SELECT s.fk_kmart_customer_id,  s.average_basket_size, s.frequency, s.high_spent_category, s.state
FROM (
SELECT AG.fk_kmart_customer_id,  AG.average_basket_size, AG.frequency,  AG.high_spent_category, AG.state,
ROW_NUMBER() OVER (PARTITION BY AG.state ORDER BY AG.frequency DESC) AS rn
FROM KSF_SOPHIA_DATA_INTELLIGENCE_HUB_PROD.SALES.AGG_CUSTOMER_INSIGHTS AG
INNER JOIN KSF_SOPHIA_DATA_INTELLIGENCE_HUB_PROD.SALES.FACT_SALES_DETAIL FSD 
ON AG.SK_AGG_CUSTOMER_INSIGHTS = FSD.FK_CUSTOMER_ID
WHERE FSD.FK_SOURCE_SYSTEM_ID = 07
) AS s
WHERE s.rn <= 1
ORDER BY s.state, s.frequency DESC
